#!/bin/sh

fileName=$1
targetDest="$(dirname "${fileName}")"
echo "targetDest = "$targetDest
outputFile="$(basename "$fileName" .wiki).pdf"
echo "outputFile = "$outputFile

echo "attempting to pandoc file"

pandoc \
  -s \
  -f vimwiki $fileName \
  -o "$targetDest/$outputFile" &&

echo "pandoc file success"
  
xreader "$targetDest/$outputFile" &
